export const FETCH_CHARACTERS = "FETCH_CHARACTERS";
export const CHARACTERS_LOADED = "CHARACTERS_LOADED";
export const SEARCH_CHARACTERS = "SEARCH_CHARACTERS";
export const SEARCH_COMPLETED = "SEARCH_COMPLETED";
export const START_EDITING = "START_EDITING";
export const EDITING_COMPLETE = "EDITING_COMPLETE";
